### ISSUE TITLE
tsgo.exe sometimes consumes 55GB(!) of memory

### ISSUE THREAD

**Issue by Zlatkovsky** [NativeScript/NativeScript#10756]
### Issue Description

When using tsgo.exe (version 7.0.0-dev.20250630.1) with the latest VS Code insider (1.102.0-insider), the memory consumed sometimes balloons to up to 55GB! (Good thing my machine has 64GB).
And even in "normal" mode, it often hovers around 18GB.

The image below was from when it was ramping up to reach 55GB eventually; this is midway through:
![Image](https://github.com/user-attachments/assets/0dafb816-704d-417e-9dfd-bd91243e2f5e)

It has also caused my VS Code to crash:
![Image](https://github.com/user-attachments/assets/b2b251b9-e025-46b8-9cef-eda16d22e205)

And on two occasions my computer froze completely and required me to forcefully reboot it (though at that time, tsgo was at a relatively lower memory consumption, so maybe that wasn't related; or at least, not to memory, but something else in tsgo/VSCode)

Version: 1.102.0-insider (user setup)
Commit: 6ccdb0f1561e1723f5ff5dfb1e3c8c037b60e700
Date: 2025-06-30T05:03:46.894Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26120

### Reproduction

This is happening on a monorepo project that has a couple hundred individual packages. I work at Microsoft, feel free to reach out to me (look me up by name, Michael Zlatkovsky).

### Relevant log output (if applicable)

```shell

```

### Environment

```yaml
OS: Windows 11 10.0.26120
CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
Shell: Not Found
node: 22.16.0
npm: 10.9.2
nativescript: Not Found

# android
java: Not Found
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: Not Found
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@typescript/native-preview": "^7.0.0-dev.20250617.1"
},
"devDependencies": {}
```

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [x] This is a bug report
- [x] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by lwears** [comment]
Just wanted to add when using the TypeScript ( Native Preview ) extension in VSCode Version: 1.102.3. MacOS 15.5, M3 Pro, relatively large codebase, tsgo is showing up in Activity Monitor as using 6.11gb memory. Whereas the old TypeScript plugin for VSCode sat at about 2gb. I am not sure if these things are related.

**Comment by NathanWalker** [comment]
Thanks for the detailed report here @Zlatkovsky and extra context @lwears. Out of curiosity if you change “moduleResolution” to “bundler” instead of “node” do you see a difference?

We’ll pull down latest insiders build this upcoming week to look.

**Comment by NathanWalker** [comment]
So far from testing on a sample project using:
```
Version: 1.103.0-insider (Universal)
Commit: 994be4137aaf18f2703037311dd1c56a8446ef8b
Date: 2025-08-01T20:53:15.562Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Darwin arm64 25.0.0
```
I see the following holding steady (I notice it's incredibly fast and snappy - very excited about tsgo). Let's hop on a chat this week to look at your case whenever convenient. I did switch my tsconfig to `"moduleResolution": "bundler"` which will become the default with v9.

<img width="1159" height="378" alt="Image" src="https://github.com/user-attachments/assets/4e1f0b32-73b7-456f-9578-ef9a8364979b" />
<img width="1104" height="472" alt="Image" src="https://github.com/user-attachments/assets/37fe7409-bb6d-441e-9942-63e65830f09b" />

**Comment by Zlatkovsky** [comment]
Hi @NathanWalker , I haven't -- in the last week -- seen the tsgo climb to more than ~4gb. Granted, that still feels like a lot. For context, we have a monorepo with probably 300ish packages inside; so, not sure if that's expected or not. So is that within what you'd expect?...

If you want to look into it further, let me know. And I can update this thread if I see it going to tens of GB again

**Comment by NathanWalker** [comment]
Let’s hop on brief call this week if you can. Mainly to coordinate the test case. We have several large monorepos I can try the same settings in but ideally we can repro with exactly what you’re working with.

Sounds high to me still so I think we can do better.

**Comment by NathanWalker** [comment]
@Zlatkovsky couldn't locate your email but feel free to ping me walkerrunpdx@gmail.com

**Comment by Zlatkovsky** [comment]
@NathanWalker , I did just experience the memory spike again, which nearly took down my computer. Fortunately, I was able to kill the task in Task Manager before it did:

<img width="742" height="227" alt="Image" src="https://github.com/user-attachments/assets/b740e9d7-030f-47c2-b4f2-d13d810aa461" />

Is there someone from within Microsoft that I could work with to investigate? I work at Microsoft, and so my repro case is a large monorepo within Microsoft. I should therefore probably only be screen-sharing it with fellow Microsofties... (Though I appreciate the offer to help!)

**Comment by harryi3t** [comment]
I am using TSGO with Cursor. I am seeing around 27GB of RAM usage.
Even when I quit the process, when it comes back, it takes around ~13 GB within a few seconds. 

<img width="1153" height="730" alt="Image" src="https://github.com/user-attachments/assets/03376f81-71ca-460e-a263-3d15a4a052f8" />

**Comment by NathanWalker** [comment]
Following up @Zlatkovsky are you still experiencing this?

**Comment by dbrxnds** [comment]
Hi, we are also running into this specifically with Cursor. Hitting 30gb is a matter of opening a few files and going to definition of trpc routes for example. Anything we can test or try to help this? 

My machine (64GB RAM available):
<img width="437" height="58" alt="Image" src="https://github.com/user-attachments/assets/088d7fc1-7c05-489b-8653-f07988581e2d" />

Colleague's machine (24GB RAM available):
<img width="1976" height="62" alt="Image" src="https://github.com/user-attachments/assets/5292ebbf-cb57-43ce-9db4-44f7a950e2ba" />

**Comment by lwears** [comment]
Hi i just wanted to report that i am still having this issue, I cannot give too much information out as its a private repo.

We have a large frontend monorepo managed with Nx and Yarn workspaces. The repository structure is organized as follows:

**Directory Structure:**
**Key Details:**
- Each directory under `/libs` and `/packages` is a separate npm workspace package with its own `package.json`
- Packages are referenced via workspace protocol in package.json dependencies (e.g., `"@org/shared-utils": "workspace:*"`)
- Nx manages the build orchestration and dependency graph between packages
- The React Native app (`/apps/mobileapp`) imports from these workspace packages the same way web apps do
- TypeScript path mappings are defined in the root `tsconfig.base.json` and extended by each app/package

**Environment:**
- Nx workspace with Yarn workspaces
- React Native + Metro bundler for mobile
- TypeScript strict mode enabled
- VS Code [insert your version info here]

Our structure follows this pattern:
```
└─apps
    └─ App name (multiple micro frontends)
└─ libs
    └─ domain
    └─ domain-shared
└─ packages
```

Our `tsconfig.json` uses `paths` mapping for workspace dependencies, and metro bundler is configured to resolve these workspace packages. 

I tried changing moduleResolution to bundler but it did not make any difference. 

Version: 1.107.0
Commit: 618725e67565b290ba4da6fe2d29f8fa1d4e3622
Date: 2025-12-10T07:43:47.883Z
Electron: 39.2.3
ElectronBuildId: 12895514
Chromium: 142.0.7444.175
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Darwin arm64 25.2.0

Extension version: 0.20251213.1

<img width="387" height="84" alt="Image" src="https://github.com/user-attachments/assets/0f812924-10a4-4b2b-91a8-989b6c00875f" />

**Comment by Konixy** [comment]
> Suddenly running into the same issue. Happy to help debug!

same after ≈4hr of coding

<img width="839" height="124" alt="Image" src="https://github.com/user-attachments/assets/887d0e67-0fb4-4a3a-bfad-b68301217cfe" />

- Cursor v2.3.41
- macOS 26.2
- tsgo 0.20260119.1

**Comment by NathanWalker** [comment]
@lwears You mentioned `The React Native app (/apps/mobileapp)` - do you have NativeScript apps in that workspace as well?

**Comment by caiofeuser** [comment]
I was having the same problem. By removing this option on my .vscode fix it. 
Looks like the the very option that should limit the memory usage was making tsgo go nuts and eat all the ram available. By removing this config it fallback to it's defult, and solve it. 

`// "typescript.tsserver.maxTsServerMemory": 6144, `

**Comment by gp27** [comment]
This bug has been fixed from tsgo version
0.20260120.1

**Comment by dbrxnds** [comment]
This bug was definitely not fixed for us. We are on latest

**Comment by hungvx-dev** [comment]
I have the same problem with 42GB memory

**Comment by nitzcard** [comment]
still happens.

**Comment by justinsmid** [comment]
I am also still experiencing this.

I don't have a single reproduction path that consistently causes this, but during a regular day's work it will creep up to 40GB and above at least a few times throughout the day.

Is there something I can do when it gets that high that would help you guys debug this? Maybe some (linux) commands I could run that would give some useful info?

Note: Removing `typescript.tsserver.maxTsServerMemory` from my vscode settings as suggested above does **not** fix it for me.

**Comment by oskarscholander** [comment]
Also experiencing this!

**Comment by puerschel93** [comment]
Using tsgo since today and it completely freezes my entire macbook after like 4-5 minutes.

**Comment by gabrielbryk** [comment]
Also having same issue. With the current ram prices I think this should be a priority issue lol

**Comment by valuin** [comment]
big boy tsgo managed to eat up 16gb of ram for me as of today

<img width="225" height="128" alt="Image" src="https://github.com/user-attachments/assets/e8d29424-c266-451b-8e44-6d230cc3c40e" />

**Comment by hyrumwhite** [comment]
Seeing this as well. Guessing its some kind of memory leak as initially its fine, but after running for some time it starts going to ~13gb vs ~600mb for tsc.

**Comment by alexspearsi** [comment]
still happens

**Comment by namhihi237** [comment]
Still happens

**Comment by zecamacho** [comment]
Giving just my experience without logs because this problem happens to a lot of people.

I've faced this problem on VSCode with Native Preview and in Zed using oxlint with typeAware (which uses tsgo underneath). Both last week.

I know tsgo is acting up because my macbook pro fans start going crazy (they are silent 99% of the time). Then tsgo shows up with 100% CPU usage on Activity Monitor.
