### ISSUE TITLE
Build error: File path too long on Windows, keep below 240 characters

### ISSUE THREAD

**Issue by nedium** [NativeScript/NativeScript#1715]
Just upgraded to 1.6 from 1.4 and i am having build issiues. 
Error is: 
`Error: File path too long on Windows, keep below 240 characters : D:\ns\NextServis\platforms\android\build\intermediates\res\merged\nativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notifications\debug\drawable-xhdpi-v4\common_google_signin_btn_text_dark_pressed.9.png`

As you can see, builder combines all plugin names next to each other and generates very long path.

Here is the build log: 

`D:\ns\NextServis>tns run android --device 0605b7ca439d06b6 --justlaunch  
Your application will be deployed only on the device specified by the provided index or identifier.
Project successfully prepared

:config phase:  createDefaultIncludeFiles
	+found plugins: nativescript-barcodescanner
	+found plugins: nativescript-google-maps-sdk
	+found plugins: nativescript-phone
	+found plugins: nativescript-push-notifications

:config phase:  createPluginsConfigFile
	+creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
	+applying configuration from: D:\ns\NextServis\platforms\android\configurations\include.gradle
	+applying configuration from: D:\ns\NextServis\platforms\android\configurations\nativescript-barcodescanner\include.gradle
	+applying configuration from: D:\ns\NextServis\platforms\android\configurations\nativescript-google-maps-sdk\include.gradle
	+applying configuration from: D:\ns\NextServis\platforms\android\configurations\nativescript-phone\include.gradle
	+applying configuration from: D:\ns\NextServis\platforms\android\configurations\nativescript-push-notifications\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: D:\ns\NextServis\platforms\android\libs\aar\barcodescanner-release.aar
	+adding dependency: D:\ns\NextServis\platforms\android\libs\aar\widgets-release.aar
:preBuild UP-TO-DATE
:preNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugBuild UP-TO-DATE
:checkNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugManifest
:preNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsReleaseBuild UP-TO-DATE
:prepareBarcodescannerReleaseLibrary UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2320Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72320Library UP-TO-DATE
:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2320Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugDependencies
:compileNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugAidl UP-TO-DATE
:compileNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugRenderscript UP-TO-DATE
:generateNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:deleteJavaDir UP-TO-DATE
:ensureMetadataOutDir UP-TO-DATE
:collectAllJars
:isMetadataGenerationNecessary UP-TO-DATE
:buildMetadata UP-TO-DATE
:copyMetadata UP-TO-DATE
:generateNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugAssets UP-TO-DATE
:mergeNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugAssets UP-TO-DATE
:generateNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugResValues UP-TO-DATE
:generateNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugResources UP-TO-DATE
:mergeNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugResources
D:\ns\NextServis\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\8.4.0\res\drawable-xhdpi\common_google_signin_btn_text_dark_pressed.9.png: Error: File path too long on Windows, keep below 240 characters : D:\ns\NextServis\platforms\android\build\intermediates\res\merged\nativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notifications\debug\drawable-xhdpi-v4\common_google_signin_btn_text_dark_pressed.9.png
:mergeNativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notificationsDebugResources FAILED

BUILD FAILED

Total time: 13.51 secs`

**Comment by enchev** [comment]
This is [known problem with npm@3](https://github.com/npm/npm/issues/3697). Maybe it will be better to use Node 4.x. More info about other benefits can be found here:
https://www.nativescript.org/blog/details/which-versions-of-node.js-should-you-use-today

**Comment by NathanaelA** [comment]
@enchev @nedium - This issue (this time) actually isn't caused by NPM!   This is caused by gradle.  Their already is a bug (https://github.com/NativeScript/android-runtime/issues/369) in for it in the Android repo when I ran into it shortly after v1.6 was released.  The good news is I figured out a work around; the bad news is that you have to do some manual editing of files.   I've been meaning to put up a blog post on it.  I'll try and get a blog post up on it today.  But the workaround is listed in the long discussion in that bug report.

**Comment by NathanaelA** [comment]
@nedium Blog post: http://fluentreports.com/blog/?p=270

**Comment by nedium** [comment]
Thanks @NathanaelA for backing. I also thought this is a gradle issue.
I was using 1.4 last fall, everything was working flawless, i had to pause the project.
I resumed last weekend, compiled and deployed and there was no errors.
Then i upgraded to lastest version (following your how to upgrade blog post).
I was unable to compile same code, same setup.

In v1.4, merged resources reside in `platforms\android\build\intermediates\res\merged\debug`
In v1.6, merged resources reside in `platforms\android\build\intermediates\res\merged\nativescript-barcodescannerNativescript-google-maps-sdkNativescript-phoneNativescript-push-notifications`

This is clearly gradle project issue, as you stated in [#369](https://github.com/NativeScript/android-runtime/issues/369)

As a workaround, for now, i will follow your technique, thanks...

**Comment by riona1** [comment]
for the error of long names you can try "Long Path Tool Program" it will fix the problem forever

**Comment by NikolaBorislavovHristov** [comment]
You can move the project folder in the root of the partition.

**Comment by nedium** [comment]
It's on minimal path "d:\ns\xx". 
No matter if it is on root of the partition, if i add one more plugin it will generate error again...

**Comment by NathanaelA** [comment]
@nedium - 
 Are you still using v1.6 -- This issue I believe is fixed in v1.8 of the CLI
Even if you want to continue running v1.6 of the runtimes; you can upgrade the nativescript cli and you should I believe get the fix.    I'm running v2.01 of the CLI; but some of my projects are using v1.8 of the runtimes...

**Comment by BenjaBoy7** [comment]
You could also try changing your build directory for your project since that is where most of the path issues will arise. In your root build.gradle file

allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    repositories {
       ...
    }
}
Android Studio will pick up on the change and still show your new build location in the Project view. It's a lot easier than moving your entire project.

**Comment by venkataiahchiripireddy** [comment]
this solue problem
allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    repositories {
        jcenter()
    }
}

**Comment by Naim28** [comment]
I would like to suggest you, try LongPathTool program to resolve this issue.
This tool is very helpful to resolve the issue.

**Comment by Albert5Brown** [comment]
Hi there, Nice answer! Or You could also try using **LongPathTool** program :-)
