### ISSUE TITLE
Navbar buttons will abruptly show up in the navbar, as opposed to fade in, on "slide" back navigation

### ISSUE THREAD

**Issue by pentool** [NativeScript/NativeScript#5361]
## Please, provide the details below:
When navigating between two pages using the "slide" transition on iOS, buttons in the navbar will fade out as you transition to the new page. So far so good. However, upon navigating back to the page you came from, but button in the navbar will not fade in. Instead, they just abruptly reappear.

You can see that the navbar title does fade in and out correctly, and the buttons also fade OUT. But they should fade IN upon navigating back to the first page.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Place a few ActionItems (buttons) in the ActionBar.
2. Use a button (or some other means) to navigate to a new page using the "slide" transition.
3. The buttons in the navbar will fade out as you go to the new page.
4. When you try to navigate back to the first page, the buttons in the navbar (ActionBar) will abruptly jump in (show up) as opposed to fade in (same way as they were fading out).

Please see this small demo on playground: https://play.nativescript.org/?template=play-js&id=k6IzKN

I also provided descriptions in the demo and they will appear on your device's screen upon launch. Please use iOS for this since I don't own an Android device and can't verify how it works there.

**Comment by NickIliev** [comment]
Hey, @pentool  testing on a real device with iOS 11.2 and the navigation backward is applying the fade effect as expected. Please let me know what device and what version of iOS you are using to experience this behavior.

**Comment by pentool** [comment]
Thanks for checking on this @NickIliev ! I only have an iTouch 5G running iOS 9.3.5. It cannot be upgraded beyond that version.

**Comment by NickIliev** [comment]
@pentool we have just released NativeScript 4.0.0 - can you try your sample with the updated version (I am currently not able to find real device with iOS 9.3.5)

**Comment by pentool** [comment]
@NickIliev Thanks, I will as soon as info is available about 4.0. At the moment I don't find any info on possible breaking changes, so I don't want to install it on my machine. As far as the playground sample goes, the NativeScript iOS apps are still in v3.4.1 so at the moment I can't test the playground sample either.

**Comment by tsonevn** [comment]
Hi @pentool,
Did you have time to test if the problem still exists while using NativeScript 4.0?

**Comment by pentool** [comment]
Yes, I have just tested this with runtime 4.0.1. Still showing the same issue.

**Comment by CatchABus** [comment]
Closing the issue as it's outdated.
