### ISSUE TITLE
showModal() does not respect animated option

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#5989]
Setting up the animated property to true on showModal method will not apply the animation for the modal page in Android. This scenario can be reproduced on the below-attached sample project.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2132173/Archive.zip)

**Comment by webleaf** [comment]
@tsonevn When will this issue be solved? It's core function and it does not work properly.
And also it will be nice if it would be possible to choose from which side Modal Page should appear (not only from bottom).

**Comment by Johanneke** [comment]
I am also waiting on this core functionality.

**Comment by tsonevn** [comment]
Hi all,
This issue is still under review. I can not commit to the exact time when the fix will be available.
Also, any PR, which provides a fix for this problem will be highly appreciated. You can check our [contribution guidelines](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md).

**Comment by kspearrin** [comment]
It's been a while. Is there any movement here?

**Comment by griffithstek** [comment]
I just implemented modals in our application. It's working great with iOS, but I've essentially had to fork the navigation between iOS and Android in order to maintain navigation animations on Android. This is an ugly solution though. Can we please bump this up the priority list?

**Comment by vahidvdn** [comment]
Any update on this?

**Comment by bradmartin** [comment]
https://github.com/NativeScript/NativeScript/issues/6232#issuecomment-521324327

@NickIliev see my comment there and if you all think that's sufficient for a PR to fix the animation not working on android when set.

**Comment by NickIliev** [comment]
@bradmartin the solution seems to work properly on first glance. Please post a PR so we could test extensively.

**Comment by webleaf** [comment]
Don't see any changes. My `fullscreen` and `animated` modals still not animated.

**Comment by bradmartin** [comment]
Seems to be working with the `@next` core-modules in my app. Maybe you haven't updated 🤔

**Comment by webleaf** [comment]
@bradmartin I've updated to 6.0.7 and see your commit there

**Comment by webleaf** [comment]
@bradmartin now it works (after several clean builds).
Now would be great to haму [ability to customize this transition](https://github.com/NativeScript/NativeScript/issues/6232#issuecomment-521324327).
