### ISSUE TITLE
[Android] App crash with "No view found for id"

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/NativeScript#8126]
Application with nested frame crash with suspend/resume during transition of parent frame.

This crash might be reproduced with various app suspend/resume scenarios. 
Isolated scenarios using [this playground app with slow transitions between pages](https://play.nativescript.org/?template=play-tsc&id=WxnOg0):

1. Steps:
   1. Go to Second Page (the second page has nested frame)
   2. Suspend app and immediately resume the same app 

2. Steps:
   1. Go to Second Page (the second page has nested frame)
   2. Go back with android back button and immediately suspend and resume the same app 

3. Steps:
   1. Go to Second Page (the second page has nested frame)
   2. Go to "Third page" and immediately suspend and resume the same app 

 
![image](https://user-images.githubusercontent.com/5860190/69324312-e65d1b80-0c50-11ea-852a-c12b7f21fc84.png)

**Comment by Firetrip** [comment]
We are having the same issue!

**Comment by manoldonev** [comment]
@Firetrip does your scenario match the steps to reproduce above? If not -- can you elaborate on your scenario as it might be a different issue that leads to the same error (but might require a different fix)?

**Comment by farfromrefug** [comment]
I just had a report of the same issue. My scenario clearly involve suspend but i don't have the exact scenario right now

**Comment by Firetrip** [comment]
@manoldonev 
my scenario is really simple.
Step 1:
Navigation from Master to Detail
Step 2:
Navigation from Detail to Master with Android Back Button
While  navigation happens, suspend app, or just tab to android task manager

**Comment by NickIliev** [comment]
@Firetrip can you let us know on what device and OS you are having the issue `No view found for id 0x6`

**Comment by dnjohnson** [comment]
I have an even simpler scenario which will crash regardless of what screen is displayed.

1. Launch app (nothing on this screen except a GridLayout and Button).
2. Suspend app by clicking home button
3. Attempt to switch back and resume app.

Crash log:

    An uncaught Exception occurred on "main" thread.
    Unable to resume activity {com.tns.nativescript.app/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment fragment2[2]<t(27)>

    StackTrace:
    java.lang.RuntimeException: Unable to resume activity {com.tns.nativescript.app/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment fragment2[2]<t(27)>
      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
      at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
      at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
      at android.os.Handler.dispatchMessage(Handler.java:107)
      at android.os.Looper.loop(Looper.java:214)
      at android.app.ActivityThread.main(ActivityThread.java:7682)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
    Caused by: java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment fragment2[2]<t(27)>
      at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
      at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
      at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
      at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
      at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
      at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
      at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
      at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
      at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:391)
      at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:517)
      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
      at android.app.Activity.performResume(Activity.java:7952)
      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
      ... 11 more

Device details:
![Screenshot_20191218-081123](https://user-images.githubusercontent.com/1211850/71035248-2db2cb00-216f-11ea-8ed1-69a4cd417587.jpg)

Appears to have been caused by the update to OxygenOS 10.0.2 - the same app was running fine prior to this update, and is still broken on 10.0.3.

**Comment by Firetrip** [comment]
@NickIliev  sorry i totally missed your question. It is happening on a Xiaomi Mi 9 EU Version with Android 10 installed. 
I just noticed that it happens in different scenarios. Not sure if it is related to the changes i implemented, but now i also can notice it with the scenario @dnjohnson  described.

**Comment by Firetrip** [comment]
Some more information.
After reverting the last changes i am unable to reproduce the issue when just switching from app to home again and again.

I had an call to firebase.areNotificationsEnabled() on my mains page ngOnInit().
in addition i accessed the secure local storage in the app.resumeEvent. One of those calls may to cause the issue. most likely the access to the storage in the app resume event.

**Comment by Firetrip** [comment]
Nevermind my previous comment.
We testet it with various devices. All Android 10 devices suffer from the crash. We really need a fix for this :/

**Comment by Firetrip** [comment]
I did some logging and debugging. 
the exception is caused by `this._currentTransaction.commitNowAllowingStateLoss();`

usually _currentTransaction is based on a fragment manager detected in view.android.js in the function `_getFragmentManager()`

I am not certain, but it seems to work as long as this function returns a fragment manager with `view._getChildFragmentManager(`, resulting in a fragmentManager looking kinda like this: 
`FragmentManager{1316099 in FragmentClass{cf2e3e4}}`

When we start committing the transaction the getter method for _currentTransaction is called another two times, basing the transaction all two times (once in the if clause, once when actually calling `this._currentTransaction.commitNowAllowingStateLoss();`) on a FragmentManager from a frameOrTabView (by calling the above mentioned view._getChildFragmentManager()).
Even before the committing the found fragment manager in the instantiateItem method is one found by view_getChildFragmentManager().


In the case of the crash however something before that goes wrong. The changeTab method is called, which in turn calls instantiateItem, which needs a fragement manager. 
Here are the steps that happen  in the view.android.js _getFragmentManager method.

1. it goes into the inner if clause of view._hasFragment, view._getChildFragmentManager() immediately. This however returns `null`. There is no other fragementManager found before that.

2. After that it of course detects that the manager property is null and uses the rootManager, which kinda looks like this when logged: `FragmentManager{35ca183 in HostCallbacks{b158d7e}}` 

This means that we now (most likely) work with the wrong FragmentManager, as it is the root manager instead of a child manager.
As soon as we try to access the currentTransaction in the if clause of the commitCurrentTransaction method, the exception is triggered and the app crashes.

Maybe that helps :)

**Comment by farfromrefug** [comment]
@Firetrip just to push your point I really think the _getFragmentManager method is wrong in the manner that it does not always return the same manager. We had that case in another issue with closing and disposing a fragment. It was fixed without fixing the _getFragmentManager method

**Comment by romandragan** [comment]
Same for me

**Comment by romandragan** [comment]
Possible solution: https://stackoverflow.com/a/8158916

**Comment by dnjohnson** [comment]
Just confirming still happening in Android 10.3.1

**Comment by deivdev** [comment]
Some workaround? or some tips?
I'm stucked here and i have no more idea.

**Comment by gurvan-guss** [comment]
I have the same when using nested Frame (NativeScript-Vue) but seems only to happen on Android 10. I tested on my Xiaomi MIUI11 and One plus Oxygen OS 10.0.1 both running on Android 10. On a Samsung phone running Android 6 no problem.

**Comment by deivdev** [comment]
so, 
i want try building with sdk 28.
I let you know.

**Comment by deivdev** [comment]
no, 
same crash error building with sdk 28.
i found this workaround, but it's so ugly.

on suspend, i throw a navigation.
when the app is resumed, it returns to the first page but 
it does not crash.


```
_app.on(_app.suspendEvent, function(args) {
  if (args.android) {
    //XXX BASTARD FIX FOR SUSPEND/RESUME BASTARD BUG
    var app_frame= _frame.getFrameById("app_frame");
    if(app_frame){
    app_frame.navigate({ moduleName: "toor/toor-page"});
    }
});
```

**Comment by dnjohnson** [comment]
After doing some playing around, I've discovered this is only happening to our app when we have a nested `page-router-outlet`.

When we change the inner route to `router-outlet` as per recommendations in the documentation then the crash no longer occurs. Of course, when we do that we lose some of the advantages of using `page-router-outlet` but it's easier to workaround them then the app crashing.

I'm unsure if this is what's causing the crash for others as well or if there are multiple scenarios.

**Comment by deivdev** [comment]
I'm currently the core implementation not the angular one.
What are the difference between `page-router-outlet `and` router-outlet` ?

**Comment by NickIliev** [comment]
The `page-router-outlet` creates a mobile navigation (for example on iOS there is a `UINavigaitonBar`) where we have an ActionBar by default. The PRO (`page-router-outlet`) also will be able to navigate back through the mobile back button (e.g. the hardware back button for Android and the Navigation's back button on iOS)

Normally, you would want to have a PRO only for your top navigation and the nested routers should use a `router-outlet` (where there is no Actionbar and no hardware back button option ad you will have to use entirely the Angular routing techniques)

**Comment by deivdev** [comment]
do you have some idea about how to fix/workaround this bug in nativescript/core ? 
my bad workaround does not cover all cases and bring always back to homepage.

**Comment by gurvan-guss** [comment]
So I'm not sure what happened there.
I made a playground with NativeScript-Vue to reproduce my problem: https://play.nativescript.org/?template=play-vue&id=1sx3qd&v=9

After I tested the playground I figured out that I didn't have the problem anymore on my Xiaomi MIUI 11.2, Android 10, SDK 29. I checked the runtime version on Playground and it was the latest `6.5.0`(released yesterday) or in my App I use the `6.4.1`. 
So I upgraded both `tns-core-module` and `tns-android` to `6.5.0` in my App and I didn't have the problem anymore.
I tested on my One Plus phone running H²OS 10.0.1, Android 10, SDK29, I still have the issue. Not sure why on that phone brand I have this problem, also I didn't update my Xiaomi phone since last time. 
I made a workaround which can be found in the playground above in `app.js` line 31,32. Like @deivdev did, every time I navigate with `navigateTo` method I will store the current navigation and in the `suspendEvent`, I will navigate to the last navigation.
However, using this workaround in my App, it will cause each time before I call `navigateTo` a white screen before navigating to the page. So right now I only use this workaround on the One Plus phone.

**Comment by douglasrmarques** [comment]
I am having the same issue. Mine is a simpler scenario just like the one @dnjohnson described.


1. Launch app 
2. Suspend app by clicking the home button
3. Attempt to switch back and resume app

**It seems to be an intermittent issue.**

I noticed here some discussion about using PRO, so I do have it set on my landing page.
Here we go with the code.

I am not sure if it's related but I was having an issue where two ActionBars were being displayed when navigating through views, then I fixed it by doing `this.page.actionBarHidden = true;` in the inner page. As a result of that, only the below ActionBar

`<ActionBar [title]="(actionBarItemVisibility=='collapse') ? ' ' : 'PDPF'" class="action-bar">
    <ActionItem visibility="{{ actionBarItemVisibility }}"> 
        <StackLayout ripple rippleColor="#c2c2c2" style="border-radius: 50;" (tap)="onDrawerButtonTap($event)">
            <Label text="&#xf0c9;" class="fas menu-icon"></Label>
        </StackLayout>
    </ActionItem>
</ActionBar>
<RadSideDrawer #rsd drawerTransition="PushTransition">
    <GridLayout tkDrawerContent rows="auto, *" class="sidedrawer sidedrawer-left">
     
    </GridLayout>
    <page-router-outlet tkMainContent class="page page-content">
    </page-router-outlet>
</RadSideDrawer>`

**Comment by a92c** [comment]
is there any news on this bug?

**Comment by a92c** [comment]
??

**Comment by a92c** [comment]
This bug is becoming frustrating. Some workaround?
The nativescript team working on it? Thank you

**Comment by mapo80** [comment]
On crashlytics I've many entries with this issue. Did you know how to solve it?

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {it.copergmps.rt.pf.android.sp.bmps/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x38 (unknown) for fragment fragment40[36]<t(4039)>
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4026)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4058)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Do I need to open another issue on GitHub?

**Comment by a92c** [comment]
Does this frustrating Nativescript bug have any team members able to fix it?

**Comment by a92c** [comment]
A reply would be much appreciated!

**Comment by grzesebe** [comment]
I’m struggling with this one too. It’s indeed very frustrating.

**Comment by farfromrefug** [comment]
Do any of you guys have a very simple repro project? Not using angular would be best.
I can look at it andfix but i need a repro project

**Comment by guilhermenasszup** [comment]
I need this feature done. Any prevision?

**Comment by NathanaelA** [comment]
Sorry guys (& gals), I just saw this issue the other day, so I have assigned it to myself to work on it.   I plan on working on this probably next week, however it might be the following week as paid support contract bugs always have a higher priority.   If any of you have a paid support plan and this is affecting you, please feel free to drop this into that support system and it will bump the priority.    Otherwise please note, we will be working on it...

1. Can any of you verify if it happens on a NS-Core / PAN application, or do you have to use Vue/Angular to see this issue?
2. Do any of you have a sample that is a PAN/Core sample that fails?
3. Does this still happen with NS 6.5

**Comment by a92c** [comment]
Hi @NathanaelA news for this bug?

**Comment by deivdev** [comment]
still happenson NS-Core

**Comment by NathanaelA** [comment]
@deivdev - Do you have a sample simple app using NSCore; the simpler the case and/or even complicated but always fails makes debugging these issues a lot easier.  :grinning:

**Comment by a92c** [comment]
when will it be fixed?

**Comment by a92c** [comment]
I need this feature done. Any prevision?

**Comment by rigor789** [comment]
> **farfromrefug**:
> Do any of you guys have a very simple repro project? Not using angular would be best.
> I can look at it andfix but i need a repro project


> **NathanaelA**:
> * Can any of you verify if it happens on a NS-Core / PAN application, or do you have to use Vue/Angular to see this issue?
> * Do any of you have a sample that is a PAN/Core sample that fails?
> * Does this still happen with NS 6.5


> **NathanaelA**
> Do you have a sample simple app using NSCore; the simpler the case and/or even complicated but always fails makes debugging these issues a lot easier. 😀

We are still missing key information @a92c - if this is blocking you, then please do share a sample we can work with...

**Comment by ruanorz** [comment]
no news related with this problem?

**Comment by rigor789** [comment]
@ruanorz no news - the questions from https://github.com/NativeScript/NativeScript/issues/8126#issuecomment-691951330 are still awaiting responses!

**Comment by grzesebe** [comment]
Hi guys, I've upgraded my project dependencies, and the problem disappeared.
Here is part of my package.json, did you tried to upgrade to ns/core 6.5.0?

```
"nativescript": {
    "tns-android": {
      "version": "6.5.0-2020-04-13-120923-01"
    },
    "tns-ios": {
      "version": "6.5.3"
    }
  },
  "dependencies": {
    "@nativescript/core": "6.5.0",
    "@nativescript/theme": "^2.3.3",
    "@panter/vue-i18next": "^0.15.2",
    "@vue/devtools": "^5.3.3",
    "axios": "^0.19.2",
    "i18next": "^19.4.5",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "nativescript-appversion": "^1.4.4",
    "nativescript-clipboard": "^2.0.0",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-image-cache-it": "^5.0.0-beta.20",
    "nativescript-inappbrowser": "^2.3.0",
    "nativescript-mapbox": "4.3.1",
    "nativescript-material-ripple": "^3.2.3",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-socketio": "^3.3.1",
    "nativescript-soft-keyboard": "^1.0.0",
    "nativescript-svg": "^1.3.7",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-vue": "^2.7.1",
    "nativescript-vue-shadow": "^0.1.0",
    "rxjs": "^6.5.5",
    "vuex": "^3.1.2"
  },
```

**Comment by dudipsh** [comment]
> page-router-outlet

works for me

**Comment by jonathan-casarrubias** [comment]
Guys I gotta be honest, one of the most frustrating problems when building apps with NativeScript is that you run into issues that have been reported for years and no one is taking care of those issues.

I understand paid support tickets must be the priority, but gosh this is a core issue and is reported since 2019 it just feels like a one man framework, we have in our application at least 7 core NativeScript libraries patched, some of the fixes we found on PRs that no body merges.

At this point it just feels like using NativeScript is a huge mistake.

**Comment by jonathan-casarrubias** [comment]
Well 1 week later I was able to get rid of the crash (Not fixing it)

Leaving notes if it can help anyone... So we had the only 2 major crashes before launching into the appstors, 1 crash for android (Related to this thread), 1 crash for iOS.

In android we get the fragment error, in iOS  "Don't know about flushed view <UIView: 0x108c72850...>"

In android was happening to us when a token expired, we redirected from the main view (With TABS) to the login section, then we use OIDC to authenticate, therefore a browser is open, while the app is trying to open the browser, our app goes to background, and at that precise moment that happens, we got the "fragments" error..

The IOS error was easier to replicate, just create the most simple basic tab navigation, with stack layouts within the items, swipe quickly between sections and it always crashes 100% without custom componentes inside each tab page..

So I changed from Tabs to BottomNavigation, the IOS crash was not happening anymore, but the Android error reported on this thread was the only remaining issue holding us from publishing.

It turned out that both crashes and some ui broken components both problems were created by Tab navigation, some were fixed when changing to BottomNavigation (Not all including this thread) so after figuring out both components are piece of a dump, we literally built a tab navigation using grid layouts, and [visibility]="expression" as toggle, and all the problems disappeared in android and iOS...

No more crashes, no more broken ui styles, no more bullshit..

So the verdict, Tab and Bottom Navigation are trash, both... Get rid of it and a list of crashes and errors will disappear.

Thanks, not

**Comment by felixkrautschuk** [comment]
This is still happening with NS 7 and even NS 8.

On my side, it is arbitrarily reproducible in an app using the material ui bottomsheet plugin, but it seems that this related to the NS core and not to the plugin.

You can find my original issue for more detailed information in the plugin repo:
https://github.com/nativescript-community/ui-material-components/issues/234

**Comment by farfromrefug** [comment]
I ll comment on this one as i have investigated this in the material components. This one is again related to the fragmentManager. Just like that issue https://github.com/NativeScript/NativeScript/issues/8037 and almost surely this one too https://github.com/NativeScript/NativeScript/issues/9034

**Comment by asiedusamuel** [comment]
Any fix yet?

**Comment by 21-razz** [comment]
I am currently having the same issue. Does anyone already fixed this issue?

`android-version`: 6.5.4
`nativescript-version`: 6.5.1

**Comment by jelledijkstra97** [comment]
Experiencing the same problem on NS8. Seems it's about time that this issue is fixed...

**Comment by felixkrautschuk** [comment]
@manoldonev @NathanaelA  I created a sample app where the issue can be reproduced (sometimes you have to susped & resume the app about 20 times until the app crahes, sometimes the crash occurs already after 4-5 attempts).

[ns-android-resume-crash.zip](https://github.com/NativeScript/NativeScript/files/6877250/ns-android-resume-crash.zip)



https://user-images.githubusercontent.com/6443021/126970311-0457414e-2849-4f15-8c83-ee6333d5f276.mov

The app uses latest NS components:
- @nativescript/core 8.0.8
- @nativescript/android 8.0.0

It contains just one page with a nested frame pointing to another page.

```
<Page navigatingTo="onPageNavigatingTo">
    <ActionBar title="Android Resume Crash"/>

    <StackLayout padding="20">
        <Label text="This Label is part of the main-page within the root-frame." textWrap="true"/>

        <StackLayout marginTop="30">
            <Frame id="customFrame" defaultPage="custom-frame-page"/>
        </StackLayout>
    </StackLayout>
</Page>
```

Log:

> JS: ############# APPLICATION SUSPEND
> JS: ############# ACTIVITY PAUSED
> JS: com.tns.NativeScriptActivity@d6bdf35
> JS: ############# ACTIVITY STOPPED
> JS: com.tns.NativeScriptActivity@d6bdf35
> JS: ############# ACTIVITY STARTED
> JS: com.tns.NativeScriptActivity@d6bdf35
> JS: ############# ACTIVITY RESUMED
> JS: com.tns.NativeScriptActivity@d6bdf35
> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Unable to resume activity {org.nativescript.nsandroidresumecrash/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x2 (unknown) for fragment fragment6[6]<Page(8)@custom-frame-page.xml:1:1;>
> System.err: 
> System.err: StackTrace:
> System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.nsandroidresumecrash/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x2 (unknown) for fragment fragment6[6]<Page(8)@custom-frame-page.xml:1:1;>
> System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
> System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
> System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
> System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
> System.err:     at android.os.Looper.loop(Looper.java:214)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
> System.err:     at java.lang.reflect.Method.invoke(Native Method)
> System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> System.err: Caused by: java.lang.IllegalArgumentException: No view found for id 0x2 (unknown) for fragment fragment6[6]<Page(8)@custom-frame-page.xml:1:1;>
> System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:315)
> System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
> System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
> System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
> System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
> System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
> System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
> System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
> System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
> System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
> System.err:     at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:447)
> System.err:     at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:458)
> System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
> System.err:     at android.app.Activity.performResume(Activity.java:7939)
> System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
> System.err:     ... 11 more
>

**Comment by lochstar** [comment]
@felixkrautschuk Thanks for puting that together. I am also having this problem on NativeScript 8 Android.

**Comment by felixkrautschuk** [comment]
I don't want to party too soon and I still need to test a bit, but for now it looks like the problem has been solved with @nativescript/core 8.1.0! At least I am not able to reproduce the issue anymore with suspending & resuming the app 50 times.

**Comment by dangrima90** [comment]
I'm working on an application where in the last couple of days we've been facing the same issue. As much as we'd like to unfortunately at this moment in time we cannot upgrade to version 8 😢. So to solve this issue in version 7, what we've done is apply the same fix done in version 8 by overriding the `Frame.onUnloaded()` function.

We are using NativeScript Vue.

**Code sample**

```js
// main.js
import { isIOS, Frame } from '@nativescript/core';
import { FrameBase } from '@nativescript/core/ui/frame/frame-common';

if (!isIOS) {
  Frame.prototype.onUnloaded = function () {
    FrameBase.prototype.onUnloaded.call(this, arguments);
  };
}
```

Thank you @felixkrautschuk for letting us know that this was fixed with version 8.1.0 as you pointed me in the right direction 😄. Fix for NativeScript 8 can be viewed [here](https://github.com/NativeScript/NativeScript/pull/8793/commits/3fbeacec41ff5068d1395e4366dda8ee65539321). From the first initial tests it seems that this has fixed our issue 🥳.

**Comment by marcuschan609** [comment]
2022-09-14 02:17:36.163 17998-17998/com.example.ofinsurance E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ofinsurance, PID: 17998
    java.lang.IllegalArgumentException: No view found for id 0x7f09014e (com.example.ofinsurance:id/nav_intro) for fragment firstFragment{7839cfc} (55ee0f31-72c5-4ed0-a6e0-facc2a887dca id=0x7f09014e)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8076)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by ThijmenL98** [comment]
Issue still exists with NS 8.3.5 and Angular 12.2.12 when using the router to switch between routes from different modules. Error only exists on Android based devices, and works fine with iOS:
```
const options: NavigationExtras = {};
if (clearHistory) {
  Object.assign(options, {clearHistory: true});
}
this.router.navigate(['some-url'], options);
```

**Comment by ThijmenL98** [comment]
After some research, the latest version of NativeScript that does NOT cause this error, is core version 8.1.5

**Comment by nikitaKulishEscola** [comment]
I had the same problem on NS (8.3) Angular (14) , after returning from an external page to the TabView, the Android app crashed.
For me, the problem with disappeared when I upgraded to these versions:
"@nativescript/core": "8.4.1",
"@nativescript/android": "8.4.0",
"@nativescript/ios": "8.4.0",

**Comment by Lengo46** [comment]
I can confirm core version 8.1.5 **is** working, core version 8.4.1 is **not** working.

**Comment by serrg1994** [comment]
I also noticed that starting from 2.5.0 (including) a lot of things was broken and I still have to use 8.1 version

**Comment by atellmer** [comment]
I have the same issue. `@nativescript/core 8.4.5`

**Comment by paul-staskiewicz** [comment]
We have the same Issue on `@nativescript/core@8.5.9`. 8.1.5 works fine. It was introduced with some of the changes to the FragmentManager in https://github.com/NativeScript/NativeScript/releases/tag/8.2.0-core.

**Comment by comporell** [comment]
I confirm having the same problem with "@nativescript/core": "~8.5.9",

**Comment by CatchABus** [comment]
Does the issue still persist? We'll need a reproducible sample for this.

**Comment by asharghi** [comment]
Yes, we are also seeing this in 8.8.6. I have a feeling it's related to Android GC cleaning away stuff that NS needs or something, because I see a lot of it happening on devices with low memory in Sentry @CatchABus

**Comment by dangrima90** [comment]
@CatchABus Following our conversation on discord, I'm adding a comment here so that it could be a reference for others in the future:

From my experience at my work place, this issue has been noted to crop up plenty of times in our production logs. This week coincidentally we managed to replicate the same issue mentioned here. Therefore I set out investigating potential causes of this issue.

I'm using NativeScript-Vue 3, and it seems that the encountered issues are specific to this flavour of NativeScript. What I did notice that the issues I managed to replicate only seemed replicable via Android 11 or less. Here is a repository with which I have managed to replicate some issues I have seen in production logs: https://github.com/dangrima90/android-navigation-issue.

Replicated issues:

* With Android 11 or lower, exiting the application via back button and accessing it again will eventually result in an error `TypeError: Cannot read properties of null (reading 'unmount')`. The error was triggered when navigating to a page with the `clearHistory` option set as true. The error is triggered from here: https://github.com/nativescript-vue/nativescript-vue/blob/d98d9bc193f11bfb0cd77e886651e9aa564504c5/src/plugins/navigation.ts#L86.

https://github.com/user-attachments/assets/822d88c6-bc85-4626-8e90-1bdc16af4b06

* Also with Android 11 when using Nested Frames, and exiting the application via back button the application crashes with the issue mentioned in this issue "No view found for id":

https://github.com/user-attachments/assets/8d1a069c-c3d7-42cd-9662-5669f1515a9c
